### ISSUE TITLE
When setting the date of a time period, such as March 12 to April 30.  The week view will be fully occupied, instead of shrinking all-day events and placing them on the top like Google Calendar, which will be more reasonable and beautiful

### ISSUE THREAD

**Issue by magicalapp** [jignesh13/googlecalendar#11]
当设置一个时间段的日期时，如3月12号到4月30号。周视图会全部占满，而不是像谷歌日历一样将全天事件缩小后放在顶部，这样会更加合理和美观![Screenshot_2021-06-12-08-44-30-310_com.example.GoogleCalendar.jpg](https://user-images.githubusercontent.com/25112746/121759926-a4f5cf00-cb5a-11eb-8a78-7c1e08309093.jpg)![Screenshot_2021-06-12-08-44-32-862_com.google.android.calendar.jpg](https://user-images.githubusercontent.com/25112746/121759929-a7f0bf80-cb5a-11eb-87d6-3668ba102ac1.jpg)

**Comment by magicalapp** [comment]
The same goes for the three day view![Screenshot_2021-06-12-08-48-18-585_com.example.GoogleCalendar.jpg](https://user-images.githubusercontent.com/25112746/121759990-fb630d80-cb5a-11eb-8647-0230342e3ec4.jpg)

**Comment by jignesh13** [comment]
![1623668845748](https://user-images.githubusercontent.com/20221469/121883144-040c3d00-cd2f-11eb-93d9-deebf5d3653a.JPEG)
issue is solved now please check latest update: ed6ced7
