### ISSUE TITLE
Swipe left and right in the day view, there will be a little bad experience.  Specifically, when the left and right swipes are close to the edge, there will be a short pause before the edge is automatically attached. It may be designed like this, but the actual experience is like a freeze. The left and right day view switching in Google Calendar is very smooth. The interface  There will be no obvious pause in the welt, it may be better to suggest a change, thank you for your effort

### ISSUE THREAD

**Issue by magicalapp** [jignesh13/googlecalendar#12]
![Video_20210612_113206_416.gif](https://user-images.githubusercontent.com/25112746/121763877-e80f6c80-cb71-11eb-9d00-7e8edb20558f.gif)
Swipe left and right in the day view, there will be a little bad experience.  Specifically, when the left and right swipes are close to the edge, there will be a short pause before the edge is automatically attached. It may be designed like this, but the actual experience is like a freeze. The left and right day view switching in Google Calendar is very smooth. The interface  There will be no obvious pause in the welt, it may be better to suggest a change, thank you for your effort

**Comment by jignesh13** [comment]
this issue is solved 
please check latest update: ed6ced7 
now everything fling smooth dayview,weekview,3-dayview etc same like google calendar
