### ISSUE TITLE
how to show single color if event is for multiple days

### ISSUE THREAD

**Issue by behappiest** [jignesh13/googlecalendar#13]
First of All thanks for this amazing work,
Although I have a usecase - 
I Have an event which is a 2 days event,
How can I show this event with single green color in month view calendar 
screenshot attached

![WhatsApp Image 2021-06-16 at 4 27 45 PM](https://user-images.githubusercontent.com/13914594/122207547-e1f5f480-cebf-11eb-8339-715f93041b93.jpeg)

**Comment by jignesh13** [comment]
please check latest commit d83d61b
now month view have support multiple day event with appropriate color for event
![Screenshot_1624176613](https://user-images.githubusercontent.com/20221469/122667399-6605f000-d1d0-11eb-93f4-9fd0451faf50.png)

please look below code
[JCalendarMonthView.java ondraw()](https://github.com/jignesh13/googlecalendar/blob/d83d61b7383c91d740bf4dc3f3513d768c68158d/app/src/main/java/com/example/GoogleCalendar/JCalendarMonthView.java#L357)
[DayModel.java](app/src/main/java/com/example/GoogleCalendar/DayModel.java) where reference of [EventInfo.java](app/src/main/java/com/example/GoogleCalendar/EventInfo.java) contain color information of appropriate event and many more thing
