### ISSUE TITLE
MonthView - first day of week

### ISSUE THREAD

**Issue by AsiaMartini** [jignesh13/googlecalendar#15]
How can I change the first day of week in month view from sunday to monday?
I gave a try but without success.

Thanks.

**Comment by jignesh13** [comment]
let me check  i can do it free for you if not take so much time otherwise i
charge for it

**Comment by AsiaMartini** [comment]
Any news?

**Comment by jignesh13** [comment]
[[JCalendarMonthView ](https://github.com/jignesh13/googlecalendar/blob/d5909b04a89c724c632e0df56015104e098e5807/app/src/main/java/com/example/GoogleCalendar/JCalendarMonthView.java#L45)]

replace line no 45 with     
private String dayname[] = {"M", "T", "W", "T", "F", "S","S"};

And 

[[MonthFragment ](https://github.com/jignesh13/googlecalendar/blob/d5909b04a89c724c632e0df56015104e098e5807/app/src/main/java/com/example/GoogleCalendar/MonthFragment.java#L49)]

add before at line no 49

page=page-1;

it will solve your issue
