### ISSUE TITLE
Multiple event in day/week/month view

### ISSUE THREAD

**Issue by sanjogshrestha** [jignesh13/googlecalendar#16]
Currently, it seems only one event can be viewed from the above view though there are multiple. I hope to get an answer on how can we show multiple events on the same day?

**Comment by jignesh13** [comment]
look screenshot it already show multiple event in date 18
![Screenshot_1643174616](https://user-images.githubusercontent.com/20221469/151108545-a8d42648-70ca-4520-a557-cf464bcd1064.png)

**Comment by sanjogshrestha** [comment]
How about as a event rather that holidays?

**Comment by jignesh13** [comment]
if you want to add event manually look [https://github.com/jignesh13/googlecalendar/blob/master/app/src/main/java/com/example/GoogleCalendar/Utility.java#L35](url) this method contain how add event you can add manually also by change logic of above method

**Comment by sanjogshrestha** [comment]
Found it. Thanks 🙏
