### ISSUE TITLE
Show more in month view

### ISSUE THREAD

**Issue by sanjogshrestha** [jignesh13/googlecalendar#17]
Is there any way we can enable users to view all the events in the month view? 
Currently, if there are say 10 events for the same day but the view only shows 5 events (assume). Is there any way we can show view more options so when clicked on it, user will be able to see all the events listed? 
Thank you!

**Comment by jignesh13** [comment]
let me check if it is possible i will update you

**Comment by sanjogshrestha** [comment]
That would be nice to have feature! Thank you! I will look forward hearing about this feature. ✌️

**Comment by jignesh13** [comment]
![1645763933131](https://user-images.githubusercontent.com/20221469/155654786-0b407890-8e1c-4b70-b8aa-e9b32a8f41b6.JPEG)

watch 17 march do you talking about look like above

**Comment by sanjogshrestha** [comment]
Yes, something like this. A better approach would be to show **+2 events** and when clicked, we show a list.

**Comment by jignesh13** [comment]
check latest commit [f242b2d](https://github.com/jignesh13/googlecalendar/commit/f242b2d3a87dd354b45081b4af7f906b00b89fc3) issue is solved now
