### ISSUE TITLE
Show weekview starting from Sunday.

### ISSUE THREAD

**Issue by sanjogshrestha** [jignesh13/googlecalendar#18]
I am unable to start my **week view** from Sunday. It always starts with the current day.
 FYI - I have tried using  
`app:firstDayOfWeek="sunday" and  app:showFirstDayOfWeekFirst="true"`

However, this does nothing. Would it be possible to start the day on Sunday? 

I appreciate your effort, thank you!

**Comment by jignesh13** [comment]
issue is solved please check latest commit [a55ea50](https://github.com/jignesh13/googlecalendar/commit/a55ea508efe1d039af9c24835355301ce088cece)

currently we also choose which is  first day of week in monthview as well please check below issue
(MonthView - first day of week #15)
