### ISSUE TITLE
Library version

### ISSUE THREAD

**Issue by dsounded** [jignesh13/googlecalendar#3]
First of all thank you for you job!

This is more like a question: 

This app allows user to switch between month, week, day view with google/custom (I believe) events. There is no such a library that have all the 3 types of views so far (at least I couldn't find anything)

Are you considering moving this to standalone library that can be used in user apps ?

**Comment by jignesh13** [comment]
Yes i thinking to move this library to month, week and days view in future i alredy try to implement month view 6 month ago but it is very difficult take lots of day if i have time in future i try my best

**Comment by jignesh13** [comment]
please check latest commit d83d61b
recently I add Schedule, Day View, MonthView, WeekView, 3-DayView same like google calendar app also you can easily switch between them and add many extra feature also.
