### ISSUE TITLE
Month view

### ISSUE THREAD

**Issue by jonasrotilli** [jignesh13/googlecalendar#4]
First of all, congratulations! Great job!
The main view is apparently in the detailed type of events / days.
Is it possible to see the month view, the one that appears every day of the month and its events?

**Comment by jignesh13** [comment]
yes it is possible and easy compare to events/days
i think it is possible using viewpager
i found repository which help to implement such kind of thing
https://github.com/developerVatsal/MyDynamicCalendarExample
if i develop such kind of thing i inform you.
Thanks!

**Comment by jignesh13** [comment]
@jonasrotilli  i successfully implement month view update repository soon thanks for inspiring me for do that

**Comment by jignesh13** [comment]
Hi @jonasrotilli 
now you can zoom in/out on calendar and enjoy new feature weekview, dayview, and 3-day view same like google calendar app

please check latest commit: b75f4f2

**Comment by jignesh13** [comment]
please check latest commit d83d61b
recently I add Schedule, Day View, MonthView, WeekView, 3-DayView same like google calendar app also you can easily switch between them and add many extra feature also.
