### ISSUE TITLE
canvas.clipRect with Region.op paramter deprecated

### ISSUE THREAD

**Issue by medonja** [jignesh13/googlecalendar#8]
Hi Jignesh,
kuds for the awesome work! :)

Note that canvas.clipRect with the Region.op parameter has been deprecated from API Level 26 in Android.

https://developer.android.com/reference/android/graphics/Canvas.html#clipRect(float,%20float,%20float,%20float,%20android.graphics.Region.Op)

You use this method quite often in WeekView. I suggest to replace all calls to canvas.clipRect with the following method:

```
private void canvasclipRect(float left, float top, float right, float bottom, Region.Op op) {
        if (op == Region.Op.REPLACE) {
            mCanvas.restore();
            mCanvas.save();
            mCanvas.clipRect(left, top, right, bottom);
            return;
        }
    }
````

Best,
Marko

**Comment by jignesh13** [comment]
thanks @medonja for suggestion i did it
please check latest commit: cea7163
